// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xiqdzqrsqfjadapvhuxd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhpcWR6cXJzcWZqYWRhcHZodXhkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxNDcyNjYsImV4cCI6MjA2NzcyMzI2Nn0.qaqkJywkWAuz--6msg5EmRKHW_EE234gEuqCNrYTD3k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});